### ISSUE TITLE
Tie in multiple voices context

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lasconic/nwc2musicxml#5] opened 2015-03-13 21:12 UTC
```
In a multiple voices context, NWCtxt format does not give much info about 
voice. It can happen that two tied notes ends up in two different MusicXML 
voices. See attach file.


```

Original issue reported on code.google.com by `lasco...@gmail.com` on 28 Feb 2011 at 1:45

Attachments:
* [bug_tie_voice.nwctxt](https://storage.googleapis.com/google-code-attachments/nwc2musicxml/issue-5/comment-0/bug_tie_voice.nwctxt)

**Comment by hedgert** [comment] 2016-05-30 21:29
The issue here appears to be NWC does the same as with Voltas - it has notation for when a tie starts, but not when a tie stops - so the Nwc2MusicXML programme at present opens ties but doesn't close them in XML.  Both MuseScore and Sibelius interpret the XML to look correct with a tie to the next note - but the XML doesn't have "stop" <tie or <tied tags.
So the fix would be to keep track of a tie being open and watch for the same note to occur, and then close it.

**Comment by hedgert** [comment] 2016-05-31 19:36
Looking further at this, I think there are two points to the original issue:
1 - ties are not terminated in XML (as per my previous post)
2 - a tie on one voice is accidentally terminated by the same note appearing in another voice (which incidentally the example files from the original post doesn't actually illustrate - but my file below does).

But, re 2, I don't think NWC can correctly handle the situation anyway (namely a tie where there are two voices and say a tie starts in voice 1, voice 2 has the same note as the tie from voice 1 (which shouldn't be the final note of the voice 1 tie), and then voice 1 has the tied note.  NWC ignores voices when it handles ties, so it displays the note in voice 2 as the end of the tie for voice 1.
So it slightly feels that by fixing this you'd be creating an ability to convert something that NWC itself cannot handle.  Here is an example of the problem:
[TiesTwoVoices.pdf](https://github.com/lasconic/nwc2musicxml/files/291940/TiesTwoVoices.pdf)
And here is the NWC file:
[TiesTwoVoices.txt](https://github.com/lasconic/nwc2musicxml/files/291944/TiesTwoVoices.txt)
This has the situation above, but the way NWC displays it is as the note in voice 2 being the end of the tie in voice 1.

The displayed music (pdf file) shows exactly what I typed in (except for the tie, which is wrongly closes on the voice 2 note)
The NWC generated file (not XML, the actual nwctxt output file) mixes up the voices - the tie starts on Pos2 but on the one that isn't Stem Down.  The next note has the same note on Pos2, but this time it's the one that isn't Stem Up - so there is enough to work out what's going on, but quite why it flips from showing voice 1 and voice 2 on one note as Pos and the next note as Pos2 with opposite stem directions!
|Chord|Dur:4th|Pos:-2|Opts:Stem=Down|Dur2:4th|Pos2:1^
|Chord|Dur:4th|Pos:2|Opts:Stem=Up|Dur2:4th|Pos2:1
|Chord|Dur:4th|Pos:1|Opts:Stem=Up|Dur2:4th|Pos2:-2

So there's enough here to handle ties across voices correctly.

**Comment by hedgert** [comment] 2016-05-31 20:00
Looking at the XML that is currently generated by Nwc2MusicXML I see that (hardly surprising given the bizarre way NWC represents voices 1 and 2 (alternating them - meaning you need to use both Pos/Pos2 and Stem=up/down to keep track of what's on each voice) Nwc2MusicXML actually gets the voices wrong.  Here are the same 3 chords across two voices form the generated XML - full XML here:
[TiesTwoVoices xml.txt](https://github.com/lasconic/nwc2musicxml/files/291996/TiesTwoVoices.xml.txt)
Picking out just the relevant note entries from the generated XML:
6 notes:
This is the G - lower voice - labelling from the top - voice 2 - but in XML labelled voice 1
          <step>G</step>
        <voice>1</voice>
        <stem>down</stem>
Next comes the D - upper voice/voice 1
          <step>D</step>
        <voice>1</voice>
        <stem>up</stem>
Then the C - still upper voice/voice 1
          <step>C</step>
        <voice>1</voice>
        <stem>up</stem>
Then the upper voice C - which isn't given a stem direction
          <step>C</step>
        <voice>2</voice>
Next the lower voice C - again no stem direction
          <step>C</step>
        <voice>2</voice>
Finally the lower voice G - also no stem direction
          <step>G</step>
        <voice>2</voice>

Unfortunately this is just wrong.  NWC doesn't help with its completely mixed up storing of notes into the file - but there is enough information in the file to work out the voices, which Nwc2MusicXML isn't doing at the moment.

What Nwc2MusicXML needs to do (reading these 3 pairs of notes) is:

- take the first note with Pos (not Pos2) as the first voice with whatever stem direction is presented (here down)
- The note on the second half of the first line is the opposite voice - voice 2
- second line: first note is Pos and Stem Up - so this is the opposite of the first note on line 1, so this should be voice 2, not voice 1 as Nwc2MusicXML currently interprets it
- note on second half of the second line is the opposite voice - voice 1
- third line: first note is Pos/Stem up - again voice 2; and second half of line is the opposite, voice 1

Question is whether making Nwc2musicXML handle this correctly would break anything else (e.g.more complex chords).
Worth a try?

**Comment by lasconic** [comment] 2016-05-31 20:02
Yes, I guess it's worth a try. With your work on junit, maybe it's better to add a couple more tests to avoid regressions. before trying to implement this.

**Comment by hedgert** [comment] 2016-05-31 20:07
Yes, although they will probably need to be tweaked as the change is made - given that in some situations Nwc2MusicXML currently produces the wrong XML (as in this example thanks for bizarre NWc behaviour).  I will do as you suggest.

**Comment by hedgert** [comment] 2016-06-01 22:32
Mmm - problem.
The first bit I've coded - ensuring that notes in different voices on chords are properly represented in XML (both the stem direction and whether the note is Pos or Pos2 need to be taken into account - which they weren't previously).
Having fixed the voices problem, Nwc2MusicXML already produces the correct XML - the problem is that neither MuseScore nor Sibelius correctly handle this situation.
The (I believe correct) XML is attached, and this is also the XML that MuseScore exports when I create the tied situation I'm testing in MuseScore.  But when I re-import it, MuseScore gets it wrong.
So I think MuseScore (and Sibelius) need bug fixes, not Nwc2MusicXML.
But as previously demonstrated you have a much better understanding of MusicXML than me - so do you agree?
This is the music I'm trying to create:
[Input3beattie.pdf](https://github.com/lasconic/nwc2musicxml/files/294476/Input3beattie.pdf)
The C in the upper voice is tied, and because the C in the second beat is in the lower voice, the tie should, and does, run until the C is repeated in voice 1.
When I get MuseScore to export this to XML this is the result:
[3 beat tie xml.txt](https://github.com/lasconic/nwc2musicxml/files/294478/3.beat.tie.xml.txt)
(in XML both the tie and tied elements start on beat 1 upper voice and end on beat 3 upper voice).
This is also the XML that I produce now from Nwc2MusicXML.

But when I re-import the XML into MuseScore (or Sibelius) it incorrectly shows the tie going to the C in voice 2, even though the XML has the tie ending on beat 3.
[TiesTwoVoices.pdf](https://github.com/lasconic/nwc2musicxml/files/294480/TiesTwoVoices.pdf)

So I think MuseScore/Sibelius are wrong on this - and that the XML should show the tie through to beat 3.

Do you agree?  (If so, I'm done with Nwc2MusicXML and will check in my changes with regression tests to manage 2 voice chords, as the problem is not with Nwc2MusicXML).

**Comment by lasconic** [comment] 2016-06-02 07:56
It's kind of a corner case in a corner case but I believe you are right. The MusicXML looks good. 
I don't know about Sibelius but I know MuseScore favor the first note it can find, even if they are in the another voice to complete the tie. So much, that if you enter the note and try to enter the tie in MuseScore, it will not let you, you will have to delete the C in voice 2 to enter the tie and then adding it back. I assume the MusicXML import uses the [same algorithm](https://github.com/musescore/MuseScore/blob/59abcf0a3cabe898846f08262882de89f1037bf8/libmscore/layout.cpp#L1595) and ignore the end note hint.

**Comment by hedgert** [comment] 2016-06-14 21:09
I think this issue is closed by the pull request/merge today.
The xml produced now handles the tie correctly - although there isn't a music package that correctly renders the xml in this situation (both Sibelius and MuseScore handle it incorrectly - as above).

**Closed** 2016-06-14 21:14 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
